# Generated by Django 5.2.9 on 2026-04-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fossa2", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="obszar",
            name="id_grupy_obszarow",
        ),
    ]
